import {useLanguage} from '../contexts/LanguageContext';

export interface MenuItem {
  id: string;
  name: string;
  description: string;
  price: number;
  isVegetarian: boolean;
  spiceLevel: 'Mild' | 'Medium' | 'Hot' | 'Extra Hot';
  isPopular: boolean;
}

export interface MenuCategory {
  id: string;
  name: string;
  icon: string;
  items: MenuItem[];
}

export const useMenu = () => {
  const {t} = useLanguage();

  const Menu: MenuCategory[] = [
    {
      id: 'appetizers',
      name: t('menuItems.appetizersStarters'),
      icon: '🥟',
      items: [
        {
          id: '1',
          name: 'Samosas',
          description:
            'Crispy triangular pastries filled with spiced potatoes and peas',
          price: 120,
          isVegetarian: true,
          spiceLevel: 'Medium',
          isPopular: true,
        },
        {
          id: '2',
          name: 'Pakoras',
          description:
            'Deep-fried fritters made with vegetables and gram flour',
          price: 100,
          isVegetarian: true,
          spiceLevel: 'Mild',
          isPopular: true,
        },
        {
          id: '3',
          name: 'Chicken Tikka',
          description:
            'Tender chicken pieces marinated in yogurt and spices, grilled to perfection',
          price: 180,
          isVegetarian: false,
          spiceLevel: 'Medium',
          isPopular: true,
        },
        {
          id: '4',
          name: 'Paneer Tikka',
          description: 'Cottage cheese cubes marinated in spices and grilled',
          price: 160,
          isVegetarian: true,
          spiceLevel: 'Medium',
          isPopular: true,
        },
        {
          id: '5',
          name: 'Aloo Tikki',
          description: 'Spiced potato patties served with chutneys',
          price: 90,
          isVegetarian: true,
          spiceLevel: 'Mild',
          isPopular: false,
        },
        {
          id: '6',
          name: 'Fish Tikka',
          description: 'Marinated fish pieces grilled with aromatic spices',
          price: 200,
          isVegetarian: false,
          spiceLevel: 'Medium',
          isPopular: true,
        },
        {
          id: '7',
          name: 'Mutton Seekh Kebab',
          description: 'Minced mutton skewers with herbs and spices',
          price: 220,
          isVegetarian: false,
          spiceLevel: 'Medium',
          isPopular: true,
        },
        {
          id: '8',
          name: 'Hara Bhara Kebab',
          description: 'Green vegetable kebabs with spinach and cottage cheese',
          price: 140,
          isVegetarian: true,
          spiceLevel: 'Mild',
          isPopular: false,
        },
        {
          id: '9',
          name: 'Chicken 65',
          description:
            'Spicy deep-fried chicken with curry leaves and red chilies',
          price: 190,
          isVegetarian: false,
          spiceLevel: 'Hot',
          isPopular: true,
        },
        {
          id: '10',
          name: 'Gobi Manchurian',
          description: 'Crispy cauliflower in tangy Manchurian sauce',
          price: 130,
          isVegetarian: true,
          spiceLevel: 'Medium',
          isPopular: true,
        },
      ],
    },
    {
      id: 'curries',
      name: 'Curries & Gravies',
      icon: '🍛',
      items: [
        {
          id: '11',
          name: 'Butter Chicken',
          description: 'Creamy tomato-based curry with tender chicken pieces',
          price: 280,
          isVegetarian: false,
          spiceLevel: 'Mild',
          isPopular: true,
        },
        {
          id: '12',
          name: 'Chicken Curry',
          description: 'Traditional Indian chicken curry with aromatic spices',
          price: 260,
          isVegetarian: false,
          spiceLevel: 'Medium',
          isPopular: true,
        },
        {
          id: '13',
          name: 'Palak Paneer',
          description: 'Cottage cheese in creamy spinach gravy',
          price: 220,
          isVegetarian: true,
          spiceLevel: 'Mild',
          isPopular: true,
        },
        {
          id: '14',
          name: 'Chana Masala',
          description: 'Spiced chickpeas in tangy tomato gravy',
          price: 180,
          isVegetarian: true,
          spiceLevel: 'Medium',
          isPopular: true,
        },
        {
          id: '15',
          name: 'Lamb Rogan Josh',
          description: 'Aromatic lamb curry from Kashmir with rich spices',
          price: 320,
          isVegetarian: false,
          spiceLevel: 'Medium',
          isPopular: false,
        },
        {
          id: '16',
          name: 'Dal Makhani',
          description: 'Creamy black lentils slow-cooked with butter and cream',
          price: 200,
          isVegetarian: true,
          spiceLevel: 'Mild',
          isPopular: true,
        },
        {
          id: '17',
          name: 'Chicken Tikka Masala',
          description: 'Grilled chicken in creamy tomato and onion gravy',
          price: 290,
          isVegetarian: false,
          spiceLevel: 'Medium',
          isPopular: true,
        },
        {
          id: '18',
          name: 'Kadai Paneer',
          description: 'Cottage cheese in spicy tomato and bell pepper gravy',
          price: 240,
          isVegetarian: true,
          spiceLevel: 'Medium',
          isPopular: true,
        },
        {
          id: '19',
          name: 'Fish Curry',
          description: 'Traditional South Indian fish curry with coconut milk',
          price: 250,
          isVegetarian: false,
          spiceLevel: 'Medium',
          isPopular: true,
        },
        {
          id: '20',
          name: 'Rajma Masala',
          description: 'Red kidney beans in rich tomato and onion gravy',
          price: 190,
          isVegetarian: true,
          spiceLevel: 'Medium',
          isPopular: true,
        },
        {
          id: '21',
          name: 'Mutton Curry',
          description: 'Tender mutton in aromatic spice blend',
          price: 300,
          isVegetarian: false,
          spiceLevel: 'Medium',
          isPopular: true,
        },
        {
          id: '22',
          name: 'Malai Kofta',
          description: 'Cottage cheese and potato dumplings in creamy gravy',
          price: 230,
          isVegetarian: true,
          spiceLevel: 'Mild',
          isPopular: true,
        },
        {
          id: '23',
          name: 'Chicken Chettinad',
          description:
            'Spicy South Indian chicken curry with coconut and spices',
          price: 270,
          isVegetarian: false,
          spiceLevel: 'Hot',
          isPopular: false,
        },
        {
          id: '24',
          name: 'Dal Tadka',
          description: 'Tempered yellow lentils with aromatic spices',
          price: 160,
          isVegetarian: true,
          spiceLevel: 'Mild',
          isPopular: true,
        },
      ],
    },
    {
      id: 'biryani',
      name: 'Biryani & Rice',
      icon: '🍚',
      items: [
        {
          id: '25',
          name: 'Chicken Biryani',
          description:
            'Fragrant basmati rice with spiced chicken and aromatic spices',
          price: 300,
          isVegetarian: false,
          spiceLevel: 'Medium',
          isPopular: true,
        },
        {
          id: '26',
          name: 'Mutton Biryani',
          description:
            'Rich biryani with tender mutton pieces and long-grain rice',
          price: 350,
          isVegetarian: false,
          spiceLevel: 'Medium',
          isPopular: true,
        },
        {
          id: '27',
          name: 'Vegetable Biryani',
          description: 'Aromatic rice with mixed vegetables and spices',
          price: 220,
          isVegetarian: true,
          spiceLevel: 'Mild',
          isPopular: true,
        },
        {
          id: '28',
          name: 'Fish Biryani',
          description: 'Fragrant rice with spiced fish and aromatic spices',
          price: 280,
          isVegetarian: false,
          spiceLevel: 'Medium',
          isPopular: true,
        },
        {
          id: '29',
          name: 'Egg Biryani',
          description: 'Aromatic rice with boiled eggs and spices',
          price: 200,
          isVegetarian: false,
          spiceLevel: 'Medium',
          isPopular: false,
        },
        {
          id: '30',
          name: 'Paneer Biryani',
          description: 'Fragrant rice with cottage cheese and aromatic spices',
          price: 240,
          isVegetarian: true,
          spiceLevel: 'Mild',
          isPopular: true,
        },
        {
          id: '31',
          name: 'Jeera Rice',
          description: 'Basmati rice tempered with cumin seeds',
          price: 120,
          isVegetarian: true,
          spiceLevel: 'Mild',
          isPopular: false,
        },
        {
          id: '32',
          name: 'Pulao',
          description: 'Mildly spiced rice with vegetables and aromatic spices',
          price: 150,
          isVegetarian: true,
          spiceLevel: 'Mild',
          isPopular: false,
        },
        {
          id: '33',
          name: 'Kashmiri Pulao',
          description: 'Aromatic rice with dry fruits and saffron',
          price: 180,
          isVegetarian: true,
          spiceLevel: 'Mild',
          isPopular: false,
        },
        {
          id: '34',
          name: 'Lemon Rice',
          description: 'South Indian rice tempered with lemon and curry leaves',
          price: 130,
          isVegetarian: true,
          spiceLevel: 'Mild',
          isPopular: false,
        },
        {
          id: '35',
          name: 'Coconut Rice',
          description: 'Fragrant rice cooked with coconut and spices',
          price: 140,
          isVegetarian: true,
          spiceLevel: 'Mild',
          isPopular: false,
        },
      ],
    },
    {
      id: 'breads',
      name: 'Breads & Rotis',
      icon: '🥖',
      items: [
        {
          id: '36',
          name: 'Naan',
          description: 'Soft leavened bread baked in tandoor',
          price: 60,
          isVegetarian: true,
          spiceLevel: 'Mild',
          isPopular: true,
        },
        {
          id: '37',
          name: 'Garlic Naan',
          description: 'Naan bread topped with garlic and herbs',
          price: 80,
          isVegetarian: true,
          spiceLevel: 'Mild',
          isPopular: true,
        },
        {
          id: '38',
          name: 'Butter Naan',
          description: 'Soft naan brushed with butter',
          price: 70,
          isVegetarian: true,
          spiceLevel: 'Mild',
          isPopular: true,
        },
        {
          id: '39',
          name: 'Roti',
          description: 'Whole wheat flatbread',
          price: 40,
          isVegetarian: true,
          spiceLevel: 'Mild',
          isPopular: true,
        },
        {
          id: '40',
          name: 'Tandoori Roti',
          description: 'Whole wheat bread baked in tandoor',
          price: 50,
          isVegetarian: true,
          spiceLevel: 'Mild',
          isPopular: true,
        },
        {
          id: '41',
          name: 'Aloo Paratha',
          description: 'Stuffed flatbread with spiced potatoes',
          price: 90,
          isVegetarian: true,
          spiceLevel: 'Mild',
          isPopular: true,
        },
        {
          id: '42',
          name: 'Paneer Paratha',
          description: 'Stuffed flatbread with cottage cheese',
          price: 100,
          isVegetarian: true,
          spiceLevel: 'Mild',
          isPopular: true,
        },
        {
          id: '43',
          name: 'Plain Paratha',
          description: 'Layered flatbread with ghee',
          price: 70,
          isVegetarian: true,
          spiceLevel: 'Mild',
          isPopular: false,
        },
        {
          id: '44',
          name: 'Kulcha',
          description: 'Soft bread with onions and spices',
          price: 90,
          isVegetarian: true,
          spiceLevel: 'Mild',
          isPopular: false,
        },
        {
          id: '45',
          name: 'Missi Roti',
          description: 'Spiced flatbread made with gram flour',
          price: 60,
          isVegetarian: true,
          spiceLevel: 'Mild',
          isPopular: false,
        },
        {
          id: '46',
          name: 'Bhatura',
          description: 'Deep-fried leavened bread',
          price: 80,
          isVegetarian: true,
          spiceLevel: 'Mild',
          isPopular: false,
        },
        {
          id: '47',
          name: 'Poori',
          description: 'Deep-fried wheat bread',
          price: 50,
          isVegetarian: true,
          spiceLevel: 'Mild',
          isPopular: false,
        },
      ],
    },
    {
      id: 'desserts',
      name: 'Desserts & Sweets',
      icon: '🍰',
      items: [
        {
          id: '48',
          name: 'Gulab Jamun',
          description: 'Soft milk dumplings in rose-flavored syrup',
          price: 120,
          isVegetarian: true,
          spiceLevel: 'Mild',
          isPopular: true,
        },
        {
          id: '49',
          name: 'Ras Malai',
          description: 'Cottage cheese dumplings in sweetened milk',
          price: 140,
          isVegetarian: true,
          spiceLevel: 'Mild',
          isPopular: true,
        },
        {
          id: '50',
          name: 'Kheer',
          description: 'Rice pudding with nuts and cardamom',
          price: 100,
          isVegetarian: true,
          spiceLevel: 'Mild',
          isPopular: true,
        },
        {
          id: '51',
          name: 'Kulfi',
          description: 'Traditional Indian ice cream with pistachios',
          price: 80,
          isVegetarian: true,
          spiceLevel: 'Mild',
          isPopular: false,
        },
        {
          id: '52',
          name: 'Jalebi',
          description: 'Crispy spiral-shaped sweet in sugar syrup',
          price: 90,
          isVegetarian: true,
          spiceLevel: 'Mild',
          isPopular: false,
        },
        {
          id: '53',
          name: 'Rasgulla',
          description: 'Soft cottage cheese balls in sugar syrup',
          price: 110,
          isVegetarian: true,
          spiceLevel: 'Mild',
          isPopular: true,
        },
        {
          id: '54',
          name: 'Barfi',
          description: 'Traditional Indian fudge with nuts and cardamom',
          price: 130,
          isVegetarian: true,
          spiceLevel: 'Mild',
          isPopular: false,
        },
        {
          id: '55',
          name: 'Ladoo',
          description: 'Sweet balls made with gram flour and sugar',
          price: 100,
          isVegetarian: true,
          spiceLevel: 'Mild',
          isPopular: false,
        },
        {
          id: '56',
          name: 'Halwa',
          description: 'Sweet semolina pudding with nuts and ghee',
          price: 120,
          isVegetarian: true,
          spiceLevel: 'Mild',
          isPopular: false,
        },
        {
          id: '57',
          name: 'Phirni',
          description: 'Rice pudding with saffron and cardamom',
          price: 110,
          isVegetarian: true,
          spiceLevel: 'Mild',
          isPopular: false,
        },
        {
          id: '58',
          name: 'Rabri',
          description: 'Thickened sweet milk with nuts and saffron',
          price: 130,
          isVegetarian: true,
          spiceLevel: 'Mild',
          isPopular: false,
        },
        {
          id: '59',
          name: 'Gajar Ka Halwa',
          description: 'Carrot pudding with milk, nuts and cardamom',
          price: 140,
          isVegetarian: true,
          spiceLevel: 'Mild',
          isPopular: true,
        },
      ],
    },
    {
      id: 'beverages',
      name: 'Beverages & Drinks',
      icon: '🥤',
      items: [
        {
          id: '60',
          name: 'Mango Lassi',
          description: 'Sweet yogurt drink with mango pulp',
          price: 80,
          isVegetarian: true,
          spiceLevel: 'Mild',
          isPopular: true,
        },
        {
          id: '61',
          name: 'Sweet Lassi',
          description: 'Traditional sweet yogurt drink',
          price: 60,
          isVegetarian: true,
          spiceLevel: 'Mild',
          isPopular: true,
        },
        {
          id: '62',
          name: 'Masala Chai',
          description: 'Spiced tea with milk and aromatic spices',
          price: 50,
          isVegetarian: true,
          spiceLevel: 'Mild',
          isPopular: true,
        },
        {
          id: '63',
          name: 'Nimbu Pani',
          description: 'Refreshing lemonade with salt and spices',
          price: 60,
          isVegetarian: true,
          spiceLevel: 'Mild',
          isPopular: false,
        },
        {
          id: '64',
          name: 'Thandai',
          description: 'Traditional spiced milk drink with nuts',
          price: 100,
          isVegetarian: true,
          spiceLevel: 'Mild',
          isPopular: false,
        },
        {
          id: '65',
          name: 'Jaljeera',
          description: 'Cumin-flavored refreshing drink',
          price: 70,
          isVegetarian: true,
          spiceLevel: 'Mild',
          isPopular: false,
        },
        {
          id: '66',
          name: 'Rose Lassi',
          description: 'Sweet yogurt drink flavored with rose syrup',
          price: 70,
          isVegetarian: true,
          spiceLevel: 'Mild',
          isPopular: false,
        },
        {
          id: '67',
          name: 'Badam Milk',
          description: 'Almond milk with saffron and cardamom',
          price: 90,
          isVegetarian: true,
          spiceLevel: 'Mild',
          isPopular: false,
        },
        {
          id: '68',
          name: 'Kesar Lassi',
          description: 'Saffron-flavored sweet yogurt drink',
          price: 100,
          isVegetarian: true,
          spiceLevel: 'Mild',
          isPopular: false,
        },
        {
          id: '69',
          name: 'Aam Panna',
          description: 'Raw mango drink with mint and spices',
          price: 80,
          isVegetarian: true,
          spiceLevel: 'Mild',
          isPopular: false,
        },
        {
          id: '70',
          name: 'Coconut Water',
          description: 'Fresh coconut water with pulp',
          price: 60,
          isVegetarian: true,
          spiceLevel: 'Mild',
          isPopular: false,
        },
        {
          id: '71',
          name: 'Sugarcane Juice',
          description: 'Fresh sugarcane juice with lemon',
          price: 50,
          isVegetarian: true,
          spiceLevel: 'Mild',
          isPopular: false,
        },
      ],
    },
    {
      id: 'street-food',
      name: 'Street Food & Chaat',
      icon: '🌶️',
      items: [
        {
          id: '72',
          name: 'Pani Puri',
          description:
            'Crispy hollow puris filled with spiced water and chutneys',
          price: 80,
          isVegetarian: true,
          spiceLevel: 'Hot',
          isPopular: true,
        },
        {
          id: '73',
          name: 'Bhel Puri',
          description: 'Puffed rice with vegetables, chutneys and sev',
          price: 90,
          isVegetarian: true,
          spiceLevel: 'Medium',
          isPopular: true,
        },
        {
          id: '74',
          name: 'Dahi Puri',
          description: 'Crispy puris filled with yogurt, chutneys and spices',
          price: 100,
          isVegetarian: true,
          spiceLevel: 'Medium',
          isPopular: true,
        },
        {
          id: '75',
          name: 'Aloo Chaat',
          description: 'Spiced potato chunks with chutneys and yogurt',
          price: 70,
          isVegetarian: true,
          spiceLevel: 'Medium',
          isPopular: true,
        },
        {
          id: '76',
          name: 'Samosa Chaat',
          description: 'Crushed samosas with chutneys, yogurt and spices',
          price: 110,
          isVegetarian: true,
          spiceLevel: 'Medium',
          isPopular: true,
        },
        {
          id: '77',
          name: 'Pav Bhaji',
          description: 'Spiced vegetable curry served with buttered bread',
          price: 120,
          isVegetarian: true,
          spiceLevel: 'Medium',
          isPopular: true,
        },
        {
          id: '78',
          name: 'Vada Pav',
          description: 'Spiced potato fritter in bread with chutneys',
          price: 60,
          isVegetarian: true,
          spiceLevel: 'Medium',
          isPopular: true,
        },
        {
          id: '79',
          name: 'Dahi Vada',
          description: 'Lentil dumplings in yogurt with chutneys',
          price: 80,
          isVegetarian: true,
          spiceLevel: 'Mild',
          isPopular: false,
        },
        {
          id: '80',
          name: 'Ragda Pattice',
          description: 'Potato patties with spiced white peas curry',
          price: 100,
          isVegetarian: true,
          spiceLevel: 'Medium',
          isPopular: false,
        },
        {
          id: '81',
          name: 'Chole Bhature',
          description: 'Spiced chickpeas with deep-fried bread',
          price: 130,
          isVegetarian: true,
          spiceLevel: 'Medium',
          isPopular: true,
        },
      ],
    },
    {
      id: 'south-indian',
      name: 'South Indian Specialties',
      icon: '🍽️',
      items: [
        {
          id: '82',
          name: 'Masala Dosa',
          description: 'Crispy rice crepe filled with spiced potatoes',
          price: 120,
          isVegetarian: true,
          spiceLevel: 'Medium',
          isPopular: true,
        },
        {
          id: '83',
          name: 'Plain Dosa',
          description: 'Crispy rice crepe served with sambar and chutney',
          price: 80,
          isVegetarian: true,
          spiceLevel: 'Mild',
          isPopular: true,
        },
        {
          id: '84',
          name: 'Rava Dosa',
          description: 'Crispy semolina crepe with onions and spices',
          price: 100,
          isVegetarian: true,
          spiceLevel: 'Mild',
          isPopular: true,
        },
        {
          id: '85',
          name: 'Idli Sambar',
          description: 'Steamed rice cakes with lentil curry',
          price: 90,
          isVegetarian: true,
          spiceLevel: 'Mild',
          isPopular: true,
        },
        {
          id: '86',
          name: 'Vada Sambar',
          description: 'Lentil fritters with spiced lentil curry',
          price: 80,
          isVegetarian: true,
          spiceLevel: 'Medium',
          isPopular: true,
        },
        {
          id: '87',
          name: 'Uttapam',
          description: 'Thick rice pancake with vegetables and spices',
          price: 110,
          isVegetarian: true,
          spiceLevel: 'Mild',
          isPopular: true,
        },
        {
          id: '88',
          name: 'Medu Vada',
          description: 'Crispy lentil fritters with coconut chutney',
          price: 70,
          isVegetarian: true,
          spiceLevel: 'Mild',
          isPopular: false,
        },
        {
          id: '89',
          name: 'Pongal',
          description: 'Creamy rice and lentil dish with ghee and spices',
          price: 100,
          isVegetarian: true,
          spiceLevel: 'Mild',
          isPopular: false,
        },
        {
          id: '90',
          name: 'Upma',
          description: 'Semolina porridge with vegetables and spices',
          price: 80,
          isVegetarian: true,
          spiceLevel: 'Mild',
          isPopular: false,
        },
        {
          id: '91',
          name: 'Appam',
          description: 'Soft rice pancakes with coconut milk',
          price: 90,
          isVegetarian: true,
          spiceLevel: 'Mild',
          isPopular: false,
        },
      ],
    },
    {
      id: 'breakfast',
      name: 'Breakfast & Snacks',
      icon: '🌅',
      items: [
        {
          id: '92',
          name: 'Aloo Paratha',
          description: 'Stuffed flatbread with spiced potatoes',
          price: 90,
          isVegetarian: true,
          spiceLevel: 'Mild',
          isPopular: true,
        },
        {
          id: '93',
          name: 'Poha',
          description: 'Flattened rice with onions, spices and peanuts',
          price: 70,
          isVegetarian: true,
          spiceLevel: 'Mild',
          isPopular: true,
        },
        {
          id: '94',
          name: 'Sabudana Khichdi',
          description: 'Tapioca pearls with potatoes, peanuts and spices',
          price: 80,
          isVegetarian: true,
          spiceLevel: 'Mild',
          isPopular: false,
        },
        {
          id: '95',
          name: 'Besan Chilla',
          description: 'Gram flour pancakes with vegetables and spices',
          price: 60,
          isVegetarian: true,
          spiceLevel: 'Mild',
          isPopular: false,
        },
        {
          id: '96',
          name: 'Dhokla',
          description: 'Steamed gram flour cakes with mustard seeds',
          price: 80,
          isVegetarian: true,
          spiceLevel: 'Mild',
          isPopular: true,
        },
        {
          id: '97',
          name: 'Khandvi',
          description: 'Rolled gram flour sheets with coconut and spices',
          price: 90,
          isVegetarian: true,
          spiceLevel: 'Mild',
          isPopular: false,
        },
        {
          id: '98',
          name: 'Thepla',
          description: 'Spiced flatbread with fenugreek leaves',
          price: 70,
          isVegetarian: true,
          spiceLevel: 'Mild',
          isPopular: false,
        },
        {
          id: '99',
          name: 'Methi Thepla',
          description: 'Fenugreek flatbread with spices and yogurt',
          price: 80,
          isVegetarian: true,
          spiceLevel: 'Mild',
          isPopular: false,
        },
        {
          id: '100',
          name: 'Moong Dal Chilla',
          description: 'Lentil pancakes with vegetables and spices',
          price: 70,
          isVegetarian: true,
          spiceLevel: 'Mild',
          isPopular: false,
        },
        {
          id: '101',
          name: 'Rava Upma',
          description: 'Semolina porridge with vegetables and spices',
          price: 80,
          isVegetarian: true,
          spiceLevel: 'Mild',
          isPopular: false,
        },
      ],
    },
  ];

  // Helpers to localize category names and item name/descriptions
  const categoryKeyById: Record<string, string> = {
    appetizers: 'appetizersStarters',
    curries: 'curriesGravies',
    biryani: 'biryaniRice',
    breads: 'breadsRotis',
    desserts: 'dessertsSweets',
    beverages: 'beveragesDrinks',
    'street-food': 'streetFoodChaat',
    'south-indian': 'southIndianSpecialties',
    breakfast: 'breakfastSnacks',
  };

  const toSlugKey = (name: string): string =>
    name
      .trim()
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, ' ')
      .split(' ')
      .filter(Boolean)
      .map((w, i) => (i === 0 ? w : w.charAt(0).toUpperCase() + w.slice(1)))
      .join('');

  const localizeItemName = (name: string): string => {
    const direct = t(`menuItemNames.${name}`);
    if (direct !== `menuItemNames.${name}`) {
      return direct;
    }
    const slug = toSlugKey(name);
    const viaSlug = t(`menuItemNames.${slug}`);
    return viaSlug !== `menuItemNames.${slug}` ? viaSlug : name;
  };

  const localizeItemDesc = (name: string, fallback: string): string => {
    const direct = t(`menuItemDescriptions.${name}`);
    if (direct !== `menuItemDescriptions.${name}`) {
      return direct;
    }
    const slug = toSlugKey(name);
    const viaSlug = t(`menuItemDescriptions.${slug}`);
    return viaSlug !== `menuItemDescriptions.${slug}` ? viaSlug : fallback;
  };

  const LocalizedMenu: MenuCategory[] = Menu.map(category => {
    const catKey = categoryKeyById[category.id] || '';
    const localizedCategoryName = catKey ? t(`menuItems.${catKey}`) : category.name;
    return {
      ...category,
      name: localizedCategoryName,
      items: category.items.map(item => ({
        ...item,
        name: localizeItemName(item.name),
        description: localizeItemDesc(item.name, item.description),
      })),
    };
  });

  return {Menu: LocalizedMenu};
};

